"""Fixing relationships and foreign keys

Revision ID: 75576fe53b0f
Revises: 11e29f90a8f5
Create Date: 2024-06-30 22:47:29.697834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75576fe53b0f'
down_revision = '11e29f90a8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
